language: node_js
node_js:
  - "10"

script: 
  - ng build --prod 
  - ng run ssr:server 
  - mv functions/dist/browser/index.html functions/dist/browser/index2.html
  - firebase deploy

cache:
  directories:
    - "node_modules"