language: node_js
node_js:
- '10'
before_script:
- npm install -g firebase-tools
- cd functions
- npm install
- cd ..
script:
- ng build --prod
- ng run ssr:server
- mv functions/dist/browser/index.html functions/dist/browser/index2.html
- firebase deploy --token FB_AUTH
cache:
  directories:
  - node_modules
env:
  global:
  - secure: FUqtZpd1TIFbAUGTv46qG4Sr75WsV//JAqKtHl5BhopMOsnR+z2sF5/LptzI+yML5T9L9tF1fg0Dcr8k7y/evnKD+a0jx3wl9drMV4WOpeh3ph89Ge+RIdVIjuELc9FH4hYjqWynY/VwRoYQCVJe57Wuad2wLH3eaNu9IX57bO4qpQs4MbhJm676cqFxoKLR0gKdjWN7HQmhchPoG9AYGiAaW144tB+vp4FLlQcn8tg2UfwjZVUE9tuKeR45NjeBfb4Mi+s75Rf4B1LoJXwLalOVNlRfSqBWDMnKp0XzRde4lgrOUuzeFhgOcnhQnSr/1eoUqHRgqEjqbKtQz/9I1ONWLPNvxRbSkhwQPDj4Qt57SNWMn1+Z1o+xGagZOEGaeEAkqgm1i7wlgVqq35HuxFK5kvA+mWkzsY+6/qU5M3el1/5PeoBke/GlsRtebQKMfdP/Ok7CTPFdwiMjFYfO8vpyC8wpxqVViX0SFYMptdgS9sjRr8F9RZeZEdBm6tmmbY5yXpxIdwgnVSpsKL2dWHeuQb1y9CsfvahH9FD8k90jkoNW1HRCiYoUQQb0eTuAk0kL2VvRcYiNoF/LFvacTqaZV4pnT5iz8d4mDDxQk0LuUqP0o6YgZ30a/uW7pcIYYXa6N6lxLL68DtBYyi/ACC5JWQCvJgsbZ4C49gCkz0s=
