language: node_js
node_js:
  - "10"

before_script:
  - npm install -g firebase-tools
  - cd functions
  - npm install
  - cd ..

script: 
  - ng build --prod 
  - ng run ssr:server 
  - ls
  - mv /functions/dist/browser/index.html /functions/dist/browser/index2.html
  - firebase deploy --token 1/5lvwj8E2Hd_A-fwy6QkDx0AeveYgqwYe5kSH71b_Z75uEaa0Y9kXKShNew00lLxE

cache:
  directories:
    - "node_modules"